travis:
  secure:
    BINSTAR_TOKEN: BNfoQ4OYYfkDrRv1pz/hiPuf+XC6Vsxi9K8QPNeqR0XuHodcG+xMKURIUPzKtAzxQPRWw+skl9RdLhEohSF/NqGisaYhK21Qgf1gISJDF5+GQUN7VA8PkyXsW0NP23LycFe7EN3iVhs15W9g0TlWCfqRSOVfV8ev8s6z5SbHmQbL9+6c3PF+UfqxIB8C+HEN0A0PXJk3jbANX8o8kGkFi7gPp0SGuDODRGT+/85FMk8+ySnUUksGUcV/2ZDiAqqcJsG66boRf7P4anMzVvCBNVaW3NEIIBbLUerm65ZylUvu7s3wazGeEcEDjezLppnSnit4z73GVYNJz5IurE25rkWpeEqLo2HN9YDt2VW3By5qbkCHqFecQ8DO6z1CWaud4VzhSFcFhi1aoUcWrJiEvji59+Z0BT6nLz4oLcU3gD/oXCq3Z7+bz5abvoj3JBCgBKwxOMlstkVUrJOJkO6RliTWT+N00eogTxbkT6fCjrpwssNXupKvE4Ctw3hMydNQ5x/Fo0VPcbP9vjm4FmzNx41sJl4l2ICCCQSQeM+ZFCicg6xEEDcaLsA/0w9PvoNjfnd7iHx+Lb3m2uyoNN7mrw9r0HadFK5Lkz3gAsfTVAyKAZLpGfmtUA+iivxAIqVyQQGQd0rwJoxMFOQ4m1miHqNlqAvD8tjSkK5pCKo6HNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
